name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: [self-hosted, 6216-uxcoreci]
    env:
      TURBO_TELEMETRY_DISABLED: 1
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 ***REMOVED***v4.2.2
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 ***REMOVED***v4.4.0
        with:
          node-version-file: .nvmrc
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Install Dependencies
        run: |
          npm ci
          npx playwright install
      - name: Run Unit Tests
        run: npm test
      - name: Run Linting
        run: npm run lint
